-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 11:36:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`roles` (
  `role_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` TEXT NOT NULL,
  `role_status` INT NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `test`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`category` (
  `category_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` TEXT NOT NULL,
  `category_status` INT NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `test`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`brand` (
  `brand_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_name` TEXT NOT NULL,
  `brand_status` INT NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `test`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`product` (
  `product_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_name` TEXT NOT NULL,
  `product_purchase_price` FLOAT(7,2) NOT NULL,
  `product_sale_price` FLOAT(7,2) NOT NULL,
  `category_id_category` BIGINT UNSIGNED NOT NULL,
  `brand_id_brand` BIGINT UNSIGNED NOT NULL,
  `product_status` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_category_idx` (`category_id_category` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `test`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  INDEX `fk_product_brand_idx` (`brand_id_brand` ASC),
  CONSTRAINT `fk_product_brand`
    FOREIGN KEY (`brand_id_brand`)
    REFERENCES `test`.`brand` (`brand_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;